@startuml classes
!theme mono
class Application {
    #FileList filelist
}

class FileList {
    #bool[] mask
    #vector<file> list
    +vector<file> get(bool isMasked = true)
    +void set(string path)
    +void filter(Filter filter)
    +void process(Process process)
}
Application *-left- FileList

struct file {
    string path
    string filetype
    double hash
}
FileList *-- file

abstract class Filter {
    +vector<file> run(vector<file> files)
}
FileList o-- Filter

abstract class Processor {
    +vector<file> run(vector<file> files)
}
FileList o-left- Processor

class GenericProcessor {
    +vector<file> run(vector<file> files)
}
Processor -down-|> GenericProcessor

class GenericFilter {
    +vector<file> run(vector<file> files)
}
Filter -down-|> GenericFilter
@enduml
