@startuml
!theme mono
start
:Получить размеры исходного изображения;
:Создать новый буфер для масштабированного изображения;
:Вычислить коэффициенты масштабирования по осям X и Y;
while (Пока не конец изображения)
    :Проходить по каждому пикселю нового изображения;
    :Найти соответствующий пиксель в исходном изображении с учетом масштабирования;
    :Получить значение цвета пикселя из исходного изображении;
    :Установить значение цвета пикселя в новом изображении;
endwhile
:Создать новый буфер с одним каналом;
while (Пока не конец изображения)
    :Преобразовать пиксели в оттенки серого;
    :Вычислить значение яркости для каждого пикселя;
    :Установить значения пикселя в новом изображении;
endwhile
:Создать вектор секторов;
while (Пока не конец изображения)
    :Проходить по каждому пикселю изображения;
    :Вычислить угол для определения сектора;
    :Определить индекс сектора для текущего пикселя;
    :Добавить значение пикселя в соответствующий сектор;
endwhile
while (Пока не конец сектора)
    :Для каждого сектора;
    if (Сектор пустой?) then (да)
        :Добавить нули в вектора статистик;
    else (нет)
        :Добавить медиану и стандартное отклонение в вектор статистик;
    endif
endwhile
while (Пока не конец сектора)
    :Для каждого сектора;
    :Вычисление хеша на основе медиан и стандартных отклонений;
    if (Разница больше порога?) then (да)
        :Установить бит хеша;
    else (нет)
        :Оставить бит хеша нулевым;
    endif
endwhile
stop
@enduml
