@startuml
!theme mono
:Пользователь: as user
(Вычисление хешей изображений) as hashing
(Дедубликация) as dedublication
(Составление списка изображений) as listing
(Просмотр изображений) as view
(Конфигурация программы) as config
(Генерация вывода) as output

(Проверка изображение ли) as isimage
(Рекурсивное составление списка) as recursion

(Установить размер стороны) as sides
(Установить интервалы) as bins
(Установить число секторов) as sectors
(Установить сигму) as sigma
(Установить предел стандартного отклонения) as deviation
(Установить предел медианы) as median
(Установить генерируемый формат) as format

(Генерация txt) as txt
(Генерация shell) as shell
(Генерация json) as json
(Генерация csv) as csv


user - dedublication
user - view
user -d- config
user -r- output
user - listing

dedublication <.. listing : <<include>>
hashing <.. config : <<include>>

listing <. recursion : <<extend>>
listing <.. hashing : <<include>>
listing <. isimage : <<include>>


config <.u. sides : <<include>>
config <.u. bins : <<include>>
config <.r. sectors : <<include>>
config <.u. sigma : <<include>>
config <.. deviation : <<include>>
config <.. median : <<include>>
config <.. format : <<include>>
config <.. recursion : <<include>>

view <.. output : <<include>>

output <-.. listing : <<include>>
output <|-l- shell
output <|-u- txt
output <|-d- json
output <|-u- csv
@enduml
